services:
  ######### Admin Portal ######### 

  gotify:
    image: ghcr.io/gotify/server
    restart: unless-stopped
    ports:
      - 7080:80
    networks:
      - gotifynet
    volumes:
      - ./data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_PASS=${MY_SECRET_PASS}
      
  ######### For App #########     

  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist
    restart: unless-stopped
    networks:
      - gotifynet
    ports:
      - 7081:8080
    volumes:
      - ./api-data:/app/data
    environment:
      # option environment see above note
      - GOTIFY_URLS=${MY_URLS}
      - GOTIFY_CLIENT_TOKENS=${MY_CLIENT_TOKEN}
      - SECNTFY_TOKENS=${MY_SECNTFY_TOKEN}
networks:
  gotifynet: null
