services:
  gotify:
    container_name: gotify
    hostname: gotify
    image: gotify/server:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - gotifynet
    ports:
      - 9980:80
    volumes:
      - ./data:/app/data
    environment:
      GOTIFY_DEFAULTUSER_PASS: ${PASS}
    env_file:
      - .env
  igotify:
    container_name: igotify
    hostname: igotify
    image: ghcr.io/androidseb25/igotify-notification-assist:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pull_policy: always
    networks:
      - gotifynet
    ports:
      - 9981:8080
    volumes:
      - ./api-data:/app/data
    environment:
      # option environment see above note
      GOTIFY_URLS: ${URLS}
      GOTIFY_CLIENT_TOKENS: ${CLIENT_TOKEN}
      SECNTFY_TOKENS: ${DEVICE_TOKEN}
    env_file:
      - .env
networks:
  gotifynet: {}
