services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - 7161:3001
    volumes:
      - /volume2/docker/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
