services:
  dockge:
    image: louislam/dockge
    container_name: Dockge-DH
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 3900:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/tsh/docker:/home/tsh/docker
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/home/tsh/docker
